### ISSUE TITLE
Error on startup: set-face-attribute: Font not available

### ISSUE THREAD

**Issue by anthrolisp** [rougier/elegant-emacs#1]
`set-face-attribute: Font not available: #<font-spec nil nil Roboto\ Mono nil nil light nil nil 14.0 nil nil nil ((:name . "Roboto Mono Light 14") (:user-spec . "Roboto Mono Light 14"))>
`

**Comment by rougier** [comment]
You need to install [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono) font on your system.
