### ISSUE TITLE
Invalid read syntax

### ISSUE THREAD

**Issue by NicoloZorzetto** [rougier/elegant-emacs#10]
Hello, I am using a Fedora machine and loading the theme via "load". I have cloned your repo in my .emacs and then with load I call the two .el files.

When I do I get an error while loading the config, in particular:

`Invalid read syntax: )`

as I understand this comes from a not matched parenthesis. The error occurs while calling both or just one. Am I doing something wrong? Loading it like in the README coul be a  problem since I use my config on multiple machines and have everything automated thru the init file

**Comment by rougier** [comment]
Weird, I do not get the problem on my side. You can try `M-x check-parens` on both files but if they're the same as the GitHub repo, that's should be fine.

Did you try with `emacs -q -l sanity.el -l elegance.el` ?
