### ISSUE TITLE
Publishing to MELPA

### ISSUE THREAD

**Issue by NicoloZorzetto** [rougier/elegant-emacs#11]
Hello Rugier, I have seen in the past couple of weeks multiple reddit users asking you to publish your theme on MELPA.
I too think that the current method is inhibiting the fruition of your great work to a lot of users.
I would love to help you do that if you'd allow me. I'd change a bit the src then create a pull request creating a new branch, maybe called "Melpa". After that I'll publish it (there's no name, it would only point to the repo and branch)

**Comment by phasmid42** [comment]
I'm not sure according to the readme this is intended to be minimalist, aka, no installation anything. 
But, anyway, if it's gonna be on melpa, I'd DEFINITELY VOTE FOR IT! 
    On Monday, August 3, 2020, 01:36:01 AM GMT+8, NicoloZorzetto <notifications@github.com> wrote:  
 
 


Hello Rugier, I have seen in the past couple of weeks multiple reddit users asking you to publish your theme on MELPA.
I too think that the current method is inhibiting the fruition of your great work to a lot of users.
I would love to help you do that if you'd allow me. I'd change a bit the src then create a pull request creating a new branch, maybe called "Melpa". After that I'll publish it (there's no name, it would only point to the repo and branch)

**Comment by NicoloZorzetto** [comment]
Hello, I have talked briefly to Nicolas on Reddit. He's very buisy and I have proposed to give him some help w/ publishing. I have rewrote the theme to comply with Melpa's requirements. All that's needed is for him to create a new branch, maybe called "Melpa" so that I can push the code. Once he said it's good we just need to create a pull request on Melpa to publish.

**Comment by NicoloZorzetto** [comment]
my bad we don't even need a new branch I just gotta say to the fetchers to only look at those files. Created a pull request
