### ISSUE TITLE
Invalid face: org-agenda-property-face

### ISSUE THREAD

**Issue by hugo-abreu** [rougier/elegant-emacs#14]
Can't use org-agenda with the following statement, in line 458 of **elegance.el**:

`(set-face 'org-agenda-property-face                     'face-faded)`

If I remove it, it works no problem. I installed the package org-agenda-property through Melpa but I still have the same problem, it doesn't seem to be related

**Comment by rougier** [comment]
Thanks for the report. This face is related to (my use of) https://github.com/Malabarba/org-agenda-property/blob/master/org-agenda-property.el and should not be present. Can you make a PR?

**Comment by mtbakerguy** [comment]
I have no idea how I missed this before.  The issue can be closed as it was fixed with changes for issue #18.
