### ISSUE TITLE
Org-agenda can't be displayed

### ISSUE THREAD

**Issue by mtbakerguy** [rougier/elegant-emacs#18]
I've reproduced this on two different installations.  Trying to run the org-agenda function leads to the following error: "Invalid face: org-agenda-property-face"

**Comment by mtbakerguy** [comment]
From an internet search, it looks like someone else ran into this on September 18th (there's a relevant post to the reddit emacs channel but the underlying content's been deleted).

**Comment by rougier** [comment]
Oh yes, that's an error, thanks. I use org-property and leave the face definition inside. Could you make  a PR?

**Comment by mtbakerguy** [comment]
Unfortunately, I don't know where to start fixing it.  While I'm not new with emacs, I've only recently started using themes at all (I used the default theme for ages).

**Comment by rougier** [comment]
The faulty line is: https://github.com/rougier/elegant-emacs/blob/master/elegance.el#L545
You can directly edit it in GitHub and add `;;`for commenting the line and GitHub will propose you to make a PR.

**Comment by mtbakerguy** [comment]
PR:  https://github.com/rougier/elegant-emacs/pull/20

**Comment by rougier** [comment]
Merged !
