### ISSUE TITLE
Font lock feature for code segments

### ISSUE THREAD

**Issue by phuhl** [rougier/elegant-emacs#24]
Hi, nice project.

In the README are screenshots of `=[C-s]=` beeing displayed as
![grafik](https://user-images.githubusercontent.com/16835755/101388830-c67eb100-38c0-11eb-8670-5f14a813ec90.png)

For me it is displayed like this, though:
![grafik](https://user-images.githubusercontent.com/16835755/101388865-d3030980-38c0-11eb-96ac-ca43a4af7cae.png)

Any idea what might be missing?

I did not include the `sanity.el` file but it did'nt appear to be the reason for this...

**Comment by rougier** [comment]
You have to `(setq org-hide-emphasis-markers t)`

**Comment by phuhl** [comment]
Thanks, that fixes it :) Didn't I see it, or is this not part of elegant-emacs? Might be a good idea to add it, in that case, so one can reproduce the images from the README without additional config.

**Comment by rougier** [comment]
Good point. Can you make a PR?
