### ISSUE TITLE
Q: Two-column view in Article.org screenshot

### ISSUE THREAD

**Issue by fpatz** [rougier/elegant-emacs#28]
Not an issue and only loosely related to this project: does anybody know, how the two-column view with full-width header and footer in the screenshot of the "Evolution of Emacs Lisp" article was created? I am not aware of ways of doing sth like that with Emacs except follow-mode (which doesn't produce that result).
https://github.com/rougier/elegant-emacs/blob/master/screenshots/screenshot-9.png#0

**Comment by rougier** [comment]
I've used [two-column](https://www.gnu.org/software/emacs/manual/html_node/emacs/Two_002dColumn.html) editing mode (+ some manual tweaking to make a nice screenshot)

**Comment by fpatz** [comment]
Ah, I see. And the screenshot was done after merging. Probably not something one would use for actually creating that kind of text, but makes for nice screenshots ;-)
BTW, elegant-emacs is cute. I'll pick up some pieces for my own Emacs setup. Thank you for that!
