### ISSUE TITLE
Company-mode???!!!

### ISSUE THREAD

**Issue by OrionRandD** [rougier/elegant-emacs#31]
Although the aim to be minimal.
What is the completion mode for this kit?
Company? Or just setting up my abbrev file?

**Comment by rougier** [comment]
I'm persoanlly using vertico/marginalia/consult. You can have a look at my configuration here: https://github.com/rougier/dotemacs

**Comment by OrionRandD** [comment]
> I'm persoanlly using vertico/marginalia/consult. You can have a look at my configuration here: https://github.com/rougier/dotemacs

Thx for sharing...
