### ISSUE TITLE
Glyphs for truncated and wrapped lines not working in Org mode.

### ISSUE THREAD

**Issue by pjhuxford** [rougier/elegant-emacs#8]
The line `(setq org-ellipsis " …")` in `elegance.el` overwrites the custom glyphs for truncated and wrapped lines defined later in the file, but only in Org mode.

One fix I have found is to replace this line with
```
(set-display-table-slot standard-display-table 'selective-display
                        (string-to-vector " …"))
```
This should also change the corresponding ellipsis in Outline mode.

**Comment by rougier** [comment]
Oh nice. I noticed the problem but did not know how to fix it ! Can you make a PR?

**Comment by pjhuxford** [comment]
[Done!](https://github.com/rougier/elegant-emacs/pull/9)

**Comment by rougier** [comment]
and merged. Thanks.
